port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- {name: ding, server: gxk2000.uicp.net, port: 5080, type: vmess, uuid: c187a5be-a885-4af1-c128-d84a7d1145f2, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /w, headers: {Host: tms.dingtalk.com}}}

rules:
  - GEOIP,CN,ding
  - MATCH,ding
