port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- {name: ding, server: gxk2000.uicp.net, port: 5080, type: vmess, uuid: c187a5be-a885-4af1-c128-d84a7d1145f2, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /w, headers: {Host: tms.dingtalk.com}}}
- {name: passwall, server: tw5.mf.dnsfailover.net, port: 10002, type: vmess, uuid: 40203d81-0f99-4fec-b124-0b5b62b5dd9b, alterId: 0, cipher: auto, tls: false, network: ws, ws-path: /, ws-headers: {Host: tw5.mf.dnsfailover.net}}
  - GEOIP,CN,ding
  - MATCH,ding
